### ISSUE TITLE
How to you your tutorial?

### ISSUE THREAD

**Issue by Sergii-Kozhushko** [in28minutes/master-spring-and-spring-boot#22]
Hi! I am new to open source community. I attentively red all files and didn't understand - How to use your tutorial? I see only code but no description or lessons.
Thanks in advance.

**Comment by pavanichunduri** [comment]
Hey ,
These are the code and files for the course https://www.udemy.com/course/spring-boot-and-spring-framework-tutorial-for-beginners/.

**Comment by Sergii-Kozhushko** [comment]
Ok, I see. The English spoken language of speaker in video is not enough good. That is real problem, the course, idea and themes looks good but it spoils everything

**Comment by in28minutes** [comment]
My experience teaching a million learners - Learners get used to the accent! 

Either way, good luck Sergii.

**Comment by Sergii-Kozhushko** [comment]
Good to hear that. I just wanted to give feedback and help.
